In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [20]:
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data,iris.target,test_size=0.2)

In [28]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9666666666666667

In [35]:
svm = SVC(gamma=5)
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

1.0

In [23]:
decision = DecisionTreeClassifier()
decision.fit(X_train,y_train)
decision.score(X_test,y_test)

0.9666666666666667

In [24]:
forest = RandomForestClassifier(n_estimators=60)
forest.fit(X_train,y_train)
forest.score(X_test,y_test)

0.9666666666666667

## Kfold cross validation


In [36]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [40]:
for train_index, test_index in kf.split([1,4,6,3,7,4,5,9,8]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [41]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [52]:
from sklearn.model_selection import StratifiedKFold
fold = StratifiedKFold(n_splits=3)

lr1 = []
svm1 = []
decision1 = []
forest1 = []


for train_index, test_index in fold.split(iris.data,iris.target):
    X_train, X_test, y_train, y_test = iris.data[train_index],iris.data[test_index],\
                                       iris.target[train_index],iris.target[test_index]
    lr1.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    svm1.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    decision1.append(get_score(DecisionTreeClassifier(),X_train,X_test,y_train,y_test))
    forest1.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))

print('Logistic Regression: ',lr1,'\n','Support Vector: ',svm1,'\n','Decision Tree : ',decision1,'\n','Random Forest: ',forest1)

d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Logistic Regression:  [0.98, 0.96, 0.98] 
 Support Vector:  [0.96, 0.98, 0.94] 
 Decision Tree :  [0.98, 0.92, 1.0] 
 Random Forest:  [0.98, 0.94, 0.98]


## cross_val_score function

In [50]:
from sklearn.model_selection import cross_val_score

In [54]:
print('logistic regression: ',cross_val_score(LogisticRegression(),iris.data,iris.target,cv=3))
print('Support Vector Machine: ',cross_val_score(SVC(),iris.data,iris.target,cv=3))
print('Decision Tree: ',cross_val_score(DecisionTreeClassifier(),iris.data,iris.target,cv=3))
print('Random Forest: ',cross_val_score(RandomForestClassifier(),iris.data,iris.target,cv=3))


d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


logistic regression:  [0.98 0.96 0.98]
Support Vector Machine:  [0.96 0.98 0.94]
Decision Tree:  [0.98 0.92 0.96]
Random Forest:  [0.98 0.94 0.98]


In [56]:
score1 = cross_val_score(LogisticRegression(),iris.data,iris.target,cv=3)
score2 = cross_val_score(SVC(),iris.data,iris.target,cv=3)
score3 = cross_val_score(DecisionTreeClassifier(),iris.data,iris.target,cv=3)
score4 = cross_val_score(RandomForestClassifier(),iris.data,iris.target,cv=3)

np.average(score1)


d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


np.float64(0.9733333333333333)

In [57]:
np.average(score2)

np.float64(0.96)

In [58]:

np.average(score3)


np.float64(0.9666666666666667)

In [59]:

np.average(score4)

np.float64(0.9666666666666667)